name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Find directories
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find exercism/go -mindepth 1 -type d | jq -R -s -c 'split("\n")[:-1] | map({directory: .})')"

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: cd ${{ matrix.directory }} && go test ./...
